services:
  - type: web
    name: logistika-frontend
    runtime: static
    rootDir: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        value: https://logistika-backend.onrender.com/api
      - key: REACT_APP_TELEGRAM_BOT_TOKEN
        sync: false # This will be set in Render environment variables for security
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 